// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpCrExlPTMMpW-ehJKd5PNw4gwZpv5jnM',
    appId: '1:85990886147:web:3d6c0bbddcefb27577b736',
    messagingSenderId: '85990886147',
    projectId: 'free-share-c0a11',
    authDomain: 'free-share-c0a11.firebaseapp.com',
    storageBucket: 'free-share-c0a11.firebasestorage.app',
    measurementId: 'G-FZ2P3L1X66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMCLStWM8HWnXFGHvMgbPUuGfBz0fz4V8',
    appId: '1:85990886147:android:4595a0d0402066f177b736',
    messagingSenderId: '85990886147',
    projectId: 'free-share-c0a11',
    storageBucket: 'free-share-c0a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLqw7DI_FUuJbX5sDg0_4V927S7Atgmy8',
    appId: '1:85990886147:ios:31707e008fc6bacc77b736',
    messagingSenderId: '85990886147',
    projectId: 'free-share-c0a11',
    storageBucket: 'free-share-c0a11.firebasestorage.app',
    iosBundleId: 'com.example.freeShareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLqw7DI_FUuJbX5sDg0_4V927S7Atgmy8',
    appId: '1:85990886147:ios:31707e008fc6bacc77b736',
    messagingSenderId: '85990886147',
    projectId: 'free-share-c0a11',
    storageBucket: 'free-share-c0a11.firebasestorage.app',
    iosBundleId: 'com.example.freeShareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpCrExlPTMMpW-ehJKd5PNw4gwZpv5jnM',
    appId: '1:85990886147:web:157008dcda31c54a77b736',
    messagingSenderId: '85990886147',
    projectId: 'free-share-c0a11',
    authDomain: 'free-share-c0a11.firebaseapp.com',
    storageBucket: 'free-share-c0a11.firebasestorage.app',
    measurementId: 'G-TLE56DNX6B',
  );
}
